FROM acos-demo-registry.cn-hangzhou.cr.aliyuncs.com/private-mesh/multica-web:latest

WORKDIR /app

USER root

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN rm -rf /app/*

COPY --chown=nextjs:nodejs .deploy-artifacts/web/standalone ./
COPY --chown=nextjs:nodejs .deploy-artifacts/web/static ./apps/web/.next/static
COPY --chown=nextjs:nodejs .deploy-artifacts/web/public ./apps/web/public

USER nextjs

EXPOSE 3000

CMD ["node", "apps/web/server.js"]
